### ISSUE TITLE
Docs: Update readme to mention this is not available for >10.15

### ISSUE THREAD

**Issue by jakewilliami** [ppamorim/fruit#3]
Title.  Am running Mojave and cannot use this screensaver.

P.S., found this repo [here](https://github.com/agarrharr/awesome-macos-screensavers) and I think it's very cool.  I have starred it to get you closer to `cask`!

**Comment by cmhdave** [comment]
Does not work on Big Sur either

**Comment by ppamorim** [comment]
@jakewilliami @cmhdave I will have a look on these, probably I need to update the configuration to support big sur.

**Comment by ppamorim** [comment]
@cmhdave It does work on Big Sur, but you will need to compile the project so far I am concerned.

**Comment by ppamorim** [comment]
Sorted!
