### ISSUE TITLE
Congrats on 50+ stars!

### ISSUE THREAD

**Issue by jamespurnama1** [ppamorim/fruit#4]
Now you can `brew cask` it 😁

**Comment by gustaferiksson** [comment]
@jamespurnama1 Unfortunately `brew cask` has increased it's requirement for acceptable casks 😢 

> An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

**Comment by jamespurnama1** [comment]
Oh no... 30 forks seems like it's too much 😢

**Comment by gustaferiksson** [comment]
It only needs to pass one of the criteria so only 20 stars to go!

**Comment by ppamorim** [comment]
@gustaferiksson It's published already with massive improvements and new fruit types :)
